module top_tb;

  // ============================================
  // Clock and Reset
  // ============================================
  logic clk;
  logic rst_n;
  
  logic [15:0] drop_cnt_check;

  initial clk = 0;
  always #5 clk = ~clk;

  // ============================================
  // Interface and DUT
  // ============================================
  bird_if vif();

  assign vif.clk = clk;

  bird dut (
    .clk(clk),
    .rst_n(vif.rst_n),
    .in_vld(vif.in_vld),
    .in_rdy(vif.in_rdy),
    .data_in(vif.data_in),
    .cfg(vif.cfg),
    .drop_cnt(drop_cnt_check),
    .local_vld(vif.local_vld),
    .local_rdy(vif.local_rdy),
    .data_local(vif.data_local),
    .remote_vld(vif.remote_vld),
    .remote_rdy(vif.remote_rdy),
    .data_remote(vif.data_remote)
  );

  // ============================================
  // Environment
  // ============================================
  bird_env env;

  // ============================================
  // Helper task to drive a packet
  // ============================================
  task send_packet(bird_packet pkt);
    $display("[TB] Sending packet...");
    pkt.display("[TB]");
    env.driver.drive_packet(pkt);
    #10;
  endtask

  // ============================================
  // Helper task to perform reset
  // ============================================
  task perform_reset(input int duration = 30);
    $display("\n[TB] ========================================");
    $display("[TB] PERFORMING RESET");
    $display("[TB] ========================================");
    
    vif.rst_n = 0;
    #duration;
    vif.rst_n = 1;
    #20;
    
    $display("[TB] Reset complete. drop_cnt = %0d", drop_cnt_check);
    $display("[TB] ========================================\n");
  endtask

  // ============================================
  // Main Test
  // ============================================
  initial begin

    // ============================================
    // Declare all packet variables at the beginning
    // ============================================
    bird_packet reset_pkt;
    bird_packet post_reset_pkt;
    bird_packet invalid_pkt;
    bird_packet reserved_pkt;
    bird_packet len0_pkt;
    bird_packet len300_pkt;
    
    logic [15:0] drop_cnt_before;
    logic [15:0] drop_cnt_after;

    // ============================================
    // Initialize
    // ============================================
    vif.rst_n = 0;
    vif.local_rdy = 1;
    vif.remote_rdy = 1;

    #20 vif.rst_n = 1;

    env = new(vif);

    fork
      env.run();
    join_none

    // Wait for environment to stabilize
    #100;

    // ============================================
    // TEST 1: Local Packets (5 packets)
    // ============================================
    $display("\n[TB] ========================================");
    $display("[TB] TEST 1: Local Packets");
    $display("[TB] ========================================");
    
    // These are generated by the generator automatically
    
    // Wait for local packets to complete
    #500;

    // ============================================
    // TEST 2: Remote Packet (In-Order)
    // ============================================
    $display("\n[TB] ========================================");
    $display("[TB] TEST 2: Remote Packet (In-Order)");
    $display("[TB] ========================================");
    
    // These are generated by the generator automatically (seq=2)
    
    #300;

    // ============================================
    // TEST 3: Remote Packet (Out-of-Order)
    // ============================================
    $display("\n[TB] ========================================");
    $display("[TB] TEST 3: Remote Packet (Out-of-Order)");
    $display("[TB] ========================================");
    
    // These are generated by the generator automatically (seq=3)
    
    #300;

    // ============================================
    // TEST 4: Invalid Packets (Drop Conditions)
    // ============================================
    $display("\n[TB] ========================================");
    $display("[TB] TEST 4: Invalid Packets (Drop Conditions)");
    $display("[TB] ========================================");
    
    // These are generated by the generator automatically
    
    #500;

    // ============================================
    // TEST 5: Mismatched SEQ_NUM
    // ============================================
    $display("\n[TB] ========================================");
    $display("[TB] TEST 5: Mismatched SEQ_NUM");
    $display("[TB] ========================================");
    
    // These are generated by the generator automatically (seq=10, then seq=11)
    
    #300;

    // ============================================
    // TEST 6: Missing Fragment
    // ============================================
    $display("\n[TB] ========================================");
    $display("[TB] TEST 6: Missing Fragment");
    $display("[TB] ========================================");
    
    // These are generated by the generator automatically (seq=20, frag 1 & 3)
    
    #300;

    // ============================================
    // TEST 7: Reset Behavior
    // ============================================
    $display("\n[TB] ========================================");
    $display("[TB] TEST 7: Reset Behavior");
    $display("[TB] ========================================");
    
    // Send a packet before reset
    reset_pkt = new();
    reset_pkt.traffic_type = 0;
    reset_pkt.seq_num = 1;
    reset_pkt.frag_num = 1;
    reset_pkt.payload_len = 3;
    reset_pkt.payload = '{8'hAA, 8'hBB, 8'hCC};
    reset_pkt.crc[0] = 0;
    reset_pkt.crc[1] = 0;
    
    $display("[TB] Sending packet BEFORE reset...");
    send_packet(reset_pkt);
    #50;
    
    // Capture drop_cnt before reset
    drop_cnt_before = drop_cnt_check;
    $display("[TB] drop_cnt before reset = %0d", drop_cnt_before);
    
    // Perform reset
    perform_reset(30);
    
    // Capture drop_cnt after reset
    drop_cnt_after = drop_cnt_check;
    $display("[TB] drop_cnt after reset = %0d", drop_cnt_after);
    
    // Verify reset cleared drop_cnt
    if (drop_cnt_after == 0) begin
      $display("[TB] ✅ RESET PASS: drop_cnt cleared to 0");
    end else begin
      $display("[TB] ❌ RESET FAIL: drop_cnt should be 0, but is %0d", drop_cnt_after);
    end
    
    // Send a packet after reset to verify functionality
    $display("[TB] Sending packet AFTER reset...");
    post_reset_pkt = new();
    post_reset_pkt.traffic_type = 0;
    post_reset_pkt.seq_num = 1;
    post_reset_pkt.frag_num = 1;
    post_reset_pkt.payload_len = 3;
    post_reset_pkt.payload = '{8'hDD, 8'hEE, 8'hFF};
    post_reset_pkt.crc[0] = 0;
    post_reset_pkt.crc[1] = 0;
    send_packet(post_reset_pkt);
    #100;

    // ============================================
    // TEST 8: Remote Packet with Maximum Values
    // ============================================
    $display("\n[TB] ========================================");
    $display("[TB] TEST 8: Remote Packet with MAX Values");
    $display("[TB] ========================================");
    
    // These are generated by the generator automatically (seq=31, len=255)
    
    #500;

    // ============================================
    // TEST 9: Drop Counter Wrap-Around
    // ============================================
    $display("\n[TB] ========================================");
    $display("[TB] TEST 9: Drop Counter Wrap-Around");
    $display("[TB] ========================================");
    
    $display("[TB] Sending 10 invalid packets to test wrap-around...");
    
    // Send 10 invalid packets (SEQ_NUM=0)
    for (int i = 0; i < 10; i++) begin
      invalid_pkt = new();
      invalid_pkt.traffic_type = 1;
      invalid_pkt.seq_num = 0;      // ❌ Invalid
      invalid_pkt.frag_num = 1;
      invalid_pkt.payload_len = 3;
      invalid_pkt.payload = '{8'hAA, 8'hBB, 8'hCC};
      invalid_pkt.crc[0] = 0;
      invalid_pkt.crc[1] = 0;
      
      send_packet(invalid_pkt);
      #20;
    end
    
    #100;

    // ============================================
    // TEST 10: Reserved Bits Non-Zero
    // ============================================
    $display("\n[TB] ========================================");
    $display("[TB] TEST 10: Reserved Bits Non-Zero");
    $display("[TB] ========================================");
    
    reserved_pkt = new();
    reserved_pkt.traffic_type = 1;
    reserved_pkt.seq_num = 50;
    reserved_pkt.frag_num = 1;
    reserved_pkt.payload_len = 3;
    reserved_pkt.payload = '{8'h11, 8'h22, 8'h33};
    reserved_pkt.reserved1 = 7'h7F;  // ❌ Reserved bits non-zero
    reserved_pkt.crc[0] = 0;
    reserved_pkt.crc[1] = 0;
    
    $display("[TB] Sending packet with NON-ZERO reserved bits...");
    reserved_pkt.display("[TB]");
    send_packet(reserved_pkt);
    
    #100;

    // ============================================
    // TEST 11: PAYLOAD_LEN = 0 and > 255
    // ============================================
    $display("\n[TB] ========================================");
    $display("[TB] TEST 11: Invalid PAYLOAD_LEN");
    $display("[TB] ========================================");
    
    // PAYLOAD_LEN = 0
    len0_pkt = new();
    len0_pkt.traffic_type = 1;
    len0_pkt.seq_num = 60;
    len0_pkt.frag_num = 1;
    len0_pkt.payload_len = 0;       // ❌ Invalid (1-255)
    len0_pkt.payload = new[0];
    len0_pkt.crc[0] = 0;
    len0_pkt.crc[1] = 0;
    
    $display("[TB] Sending packet with PAYLOAD_LEN=0...");
    len0_pkt.display("[TB]");
    send_packet(len0_pkt);
    #50;
    
    // PAYLOAD_LEN = 300
    len300_pkt = new();
    len300_pkt.traffic_type = 1;
    len300_pkt.seq_num = 61;
    len300_pkt.frag_num = 1;
    len300_pkt.payload_len = 300;   // ❌ Invalid (1-255)
    len300_pkt.payload = new[300];
    for (int i = 0; i < 300; i++) begin
      len300_pkt.payload[i] = i[7:0];
    end
    len300_pkt.crc[0] = 0;
    len300_pkt.crc[1] = 0;
    
    $display("[TB] Sending packet with PAYLOAD_LEN=300...");
    len300_pkt.display("[TB]");
    send_packet(len300_pkt);
    #100;

    // ============================================
    // Wait for scoreboard to process all packets
    // ============================================
    #500;

    // ============================================
    // Print Final Report
    // ============================================
    env.sb.report(); 

    $display("\n[TB] ========================================");
    $display("[TB] TEST FINISHED");
    $display("[TB] Final drop_cnt = %0d", drop_cnt_check);
    $display("[TB] ========================================\n");
    $finish;

  end

  // ============================================
  // Monitor drop_cnt for debugging
  // ============================================
  always @(posedge clk) begin
    if (vif.rst_n && drop_cnt_check !== 0) begin
      // Uncomment for debugging
      // $display("[TB] drop_cnt = %0d at time %0t", drop_cnt_check, $time);
    end
  end

endmodule
